#!/usr/bin/env python3
"""Emit questions 101-300 as a JS array snippet."""

T1 = "Signals, Signs, Intersections & Right-of-Way"
T2 = "Passing, Lanes, Bikes, Motorcycles, Trucks & Emergency Vehicles"
T3 = "Speed, Weather, Visibility, Emergencies & Safe Driving"
T4 = "DUI, Phones, Seat Belts, Collisions, Records & Important Numbers"

# prompt, A, B, C, answer letter, topic
ROWS = [
(101, T1, "What should you do when approaching a flashing yellow traffic signal?",
 "Stop before proceeding", "Slow down and proceed with caution", "Speed up before it changes", "B"),
(102, T1, "A flashing red traffic signal should be treated like:",
 "A YIELD sign", "A STOP sign", "A green light", "B"),
(103, T1, "A solid yellow traffic signal means:",
 "Stop if you can do so safely", "Always continue through the intersection", "Speed up to clear the intersection", "A"),
(104, T1, "A flashing yellow arrow means:",
 "The turn is prohibited", "You may turn after yielding to oncoming traffic", "You have a protected turn", "B"),
(105, T1, "A green arrow means:",
 "You may proceed in the arrow's direction", "You must yield to all oncoming vehicles", "Stop before turning", "A"),
(106, T1, "At a red arrow, you must:",
 "Turn after stopping if clear", "Remain stopped until a green signal or green arrow appears", "Treat it like a flashing red light", "B"),
(107, T1, "A traffic signal is completely dark because of a power failure. You should:",
 "Drive through slowly", "Treat it as an all-way STOP", "Yield only to traffic on your left", "B"),
(108, T1, "At a STOP sign, where should you stop if there is a limit line?",
 "After the line", "At the limit line", "In the middle of the crosswalk", "B"),
(109, T1, "If there is no limit line or crosswalk at a STOP sign, stop:",
 "Before entering the intersection", "50 feet from the intersection", "After entering the intersection", "A"),
(110, T1, "A YIELD sign means:",
 "Always stop", "Slow down and be ready to stop for traffic, bicyclists, or pedestrians", "You always have priority", "B"),
(111, T1, "A five-sided traffic sign indicates:",
 "Railroad crossing", "School area", "Hospital", "B"),
(112, T1, "A diamond-shaped sign generally:",
 "Gives a warning", "Indicates a speed limit", "Indicates a one-way street", "A"),
(113, T1, "A circular yellow-and-black railroad sign means:",
 "Railroad crossing ahead", "No trains allowed", "Railroad parking area", "A"),
(114, T1, "A red circle with a diagonal red line means:",
 "The action shown is required", "The action shown is prohibited", "The action shown is recommended", "B"),
(115, T1, "If you see WRONG WAY signs because you entered against traffic, you should:",
 "Continue until the next exit", "Safely back out or turn around", "Move to the left lane", "B"),
(116, T1, "At night, red road reflectors shining toward you may indicate:",
 "A school zone", "You are traveling in the wrong direction", "A construction zone", "B"),
(117, T1, "A white rectangular regulatory sign usually:",
 "Gives rules that must be obeyed", "Warns of recreational areas", "Marks railroad crossings", "A"),
(118, T1, "Who has the right-of-way in a marked crosswalk?",
 "Vehicles", "Pedestrians", "Whoever is moving faster", "B"),
(119, T1, "Do pedestrians have right-of-way in unmarked crosswalks?",
 "No", "Yes", "Only at night", "B"),
(120, T1, "You approach a crosswalk where another vehicle has stopped. You should:",
 "Pass the vehicle carefully", "Not pass because a pedestrian may be crossing", "Honk and continue", "B"),
(121, T1, "A pedestrian makes eye contact with you at a crosswalk. You should:",
 "Assume they will wait", "Yield because they may be preparing to cross", "Honk", "B"),
(122, T1, "A pedestrian with a white cane is waiting to cross. You should:",
 "Honk to let them know you are there", "Give them the right-of-way", "Drive around them", "B"),
(123, T1, "Should you honk at a blind pedestrian to alert them?",
 "Yes", "No", "Only at night", "B"),
(124, T1, "A blind pedestrian pulls in their cane and steps away from the intersection. This usually means:",
 "They want you to stop", "You may proceed", "They are about to cross", "B"),
(125, T1, "At an uncontrolled intersection, the vehicle arriving first generally:",
 "Has the right-of-way", "Must yield", "Must wait for the vehicle on the left", "A"),
(126, T1, "Two vehicles reach an uncontrolled intersection simultaneously. You should yield to:",
 "The vehicle on your left", "The vehicle on your right", "The smaller vehicle", "B"),
(127, T1, "At a T-intersection without STOP or YIELD signs:",
 "Traffic on the terminating road has priority", "Traffic on the through road has priority", "Left-turning traffic always has priority", "B"),
(128, T1, "When making a left turn, you must yield to:",
 "Approaching traffic close enough to be dangerous", "Only motorcycles", "Vehicles behind you", "A"),
(129, T1, "When making a right turn, you should especially check for:",
 "Pedestrians, bicyclists, and motorcycles", "Only cars behind you", "Trains", "A"),
(130, T1, "You have a green light, but traffic is blocking the intersection. You should:",
 "Enter and wait", "Remain outside until you can completely cross", "Honk until traffic moves", "B"),
(131, T1, "Before entering a roundabout, you should:",
 "Accelerate", "Slow down and yield to traffic already inside", "Stop inside the roundabout", "B"),
(132, T1, "Traffic in a roundabout travels:",
 "Clockwise", "Counter-clockwise", "In either direction", "B"),
(133, T1, "Should you normally stop while inside a roundabout?",
 "Yes", "No", "Only before each exit", "B"),
(134, T1, "Can you pass another vehicle while traveling through a roundabout?",
 "Yes", "No", "Only on the left", "B"),
(135, T1, "When exiting a roundabout, you should:",
 "Signal", "Honk", "Stop first", "A"),
(136, T1, "If you miss your roundabout exit:",
 "Reverse", "Continue around to the exit again", "Stop and make a U-turn", "B"),
(137, T1, "Two vehicles meet on a steep narrow road. Which has right-of-way?",
 "Vehicle facing downhill", "Vehicle facing uphill", "Heavier vehicle", "B"),
(138, T1, "Why should the downhill-facing vehicle normally back up?",
 "It has better control while backing uphill", "It has weaker brakes", "California requires all downhill vehicles to reverse", "A"),
(139, T1, "A funeral procession led by a traffic officer:",
 "Has the right-of-way", "Must yield to all vehicles", "Can be interrupted when traffic is heavy", "A"),
(140, T1, "You may interfere with a funeral procession:",
 "When you have a green light", "When late for an appointment", "Never", "C"),
(141, T1, "If a police officer directs you contrary to a traffic signal, obey:",
 "The traffic signal", "The police officer", "Whichever seems safer", "B"),
(142, T1, "The same rule applies to directions from:",
 "A firefighter", "Any pedestrian", "Another driver", "A"),
(143, T1, "Before entering an intersection, you should look:",
 "Left only", "Left, right, and ahead", "In the rearview mirror only", "B"),
(144, T1, "Right-of-way should be given up when doing so:",
 "Helps prevent a collision", "Makes you late", "Allows you to speed", "A"),
(145, T1, "A green light gives you permission to:",
 "Proceed regardless of pedestrians", "Proceed when the intersection is safe and clear", "Ignore bicyclists", "B"),
(146, T1, "At a flashing DON'T WALK signal, a pedestrian should:",
 "Start crossing quickly", "Not begin crossing", "Run across", "B"),
(147, T1, "Drivers must still yield to a pedestrian already crossing when DON'T WALK begins flashing:",
 "True", "False", "Only in school zones", "A"),
(148, T1, "If there is no pedestrian signal, pedestrians should obey:",
 "Vehicle traffic signals", "Other pedestrians", "Parked vehicles", "A"),
(149, T1, "A WALK signal means:",
 "Pedestrians may cross", "Vehicles may turn without yielding", "Pedestrians must wait", "A"),
(150, T1, "A countdown pedestrian signal displays:",
 "Speed limit", "Seconds remaining for crossing", "Distance across the road", "B"),
(151, T2, "You should not pass within how many feet of an intersection?",
 "50 feet", "100 feet", "200 feet", "B"),
(152, T2, "You should not pass within 100 feet of:",
 "An intersection, bridge, tunnel, or railroad crossing", "A gas station", "A driveway only", "A"),
(153, T2, "When approaching a hill or curve where you cannot see oncoming traffic:",
 "Pass quickly", "Do not pass", "Honk before passing", "B"),
(154, T2, "For a hill or curve to provide adequate visibility for passing, the handbook says it should be at least approximately:",
 "One-tenth mile ahead", "One-third mile ahead", "One mile ahead", "B"),
(155, T2, "Before passing another vehicle, check:",
 "Your blind spot", "Your fuel gauge", "Your radio", "A"),
(156, T2, "When another vehicle is passing you:",
 "Speed up", "Maintain your lane position and speed", "Move into the passing lane", "B"),
(157, T2, "May you drive off the paved roadway to pass another vehicle?",
 "Yes", "No", "Only during daylight", "B"),
(158, T2, "Passing on the right may be allowed when:",
 "A highway has two or more lanes in your direction", "There is only a dirt shoulder", "You must leave the pavement", "A"),
(159, T2, "You may also pass on the right when the vehicle ahead:",
 "Is signaling a left turn and passing can be done safely", "Is speeding", "Has emergency flashers on", "A"),
(160, T2, "On a one-way street, passing on the right:",
 "May be permitted when safe", "Is always illegal", "Requires driving on the sidewalk", "A"),
(161, T2, "A bicyclist generally has:",
 "Fewer road rights than motorists", "The same rights and responsibilities as other drivers", "No right to use traffic lanes", "B"),
(162, T2, "Bicyclists should normally travel:",
 "Against traffic", "In the same direction as traffic", "On whichever side has less traffic", "B"),
(163, T2, "A bicyclist under age 18 must:",
 "Wear a helmet", "Ride only on sidewalks", "Ride with an adult", "A"),
(164, T2, "A bicyclist may move left to:",
 "Avoid hazards", "Block traffic", "Prevent vehicles from passing", "A"),
(165, T2, "A bicyclist may use a crosswalk by:",
 "Riding through at full speed", "Stopping and crossing as a pedestrian", "Ignoring pedestrian signals", "B"),
(166, T2, "A bicycle's white front light at night must be visible from:",
 "100 feet", "200 feet", "300 feet", "C"),
(167, T2, "A bicycle's rear red reflector/light must be visible from:",
 "300 feet", "500 feet", "1,000 feet", "B"),
(168, T2, "Bicycle pedal/shoe/ankle reflectors must be visible from:",
 "100 feet", "200 feet", "500 feet", "B"),
(169, T2, "When you cannot change lanes while passing a bicyclist, leave at least:",
 "1 foot", "2 feet", "3 feet", "C"),
(170, T2, "If you cannot provide three feet when passing a bicyclist:",
 "Pass slowly anyway", "Do not pass until you can provide sufficient clearance", "Honk until the cyclist stops", "B"),
(171, T2, "Before turning right across a bicycle lane:",
 "Merge safely behind the bicyclist", "Race ahead of the bicyclist", "Stop in the bicycle lane", "A"),
(172, T2, "You may enter a bicycle lane to prepare for a turn no more than:",
 "100 feet beforehand", "200 feet beforehand", "500 feet beforehand", "B"),
(173, T2, "Motorcyclists:",
 "Have fewer rights than cars", "Have the same rights and responsibilities as other drivers", "Must always yield to cars", "B"),
(174, T2, "The recommended following distance behind a motorcycle is:",
 "One second", "Two seconds", "Three seconds", "C"),
(175, T2, "You should attempt to pass a motorcycle within the same lane:",
 "Never", "Whenever the lane is wide", "Only below 25 mph", "A"),
(176, T2, "California allows motorcycles to travel between lanes, known as:",
 "Lane splitting", "Lane blocking", "Lane hopping", "A"),
(177, T2, "Before opening your door next to traffic, check for:",
 "Motorcycles and bicyclists", "Only trucks", "Only pedestrians", "A"),
(178, T2, "A truck's large blind spots are often called:",
 "Red Zones", "No Zones", "Passing Zones", "B"),
(179, T2, "If you cannot see a truck's side mirrors:",
 "The truck driver cannot see you", "You are definitely visible", "You should follow closer", "A"),
(180, T2, "Which generally requires more stopping distance at the same speed?",
 "Passenger car", "Large truck", "Motorcycle", "B"),
(181, T2, "At 55 mph, an average passenger vehicle can stop within approximately:",
 "100 feet", "300 feet", "600 feet", "B"),
(182, T2, "A large vehicle traveling 55 mph can take up to approximately:",
 "200 feet", "300 feet", "400 feet", "C"),
(183, T2, "Loaded trucks generally stop:",
 "Faster than empty trucks", "Slower than empty trucks", "At exactly the same distance", "B"),
(184, T2, "Why might a truck swing left before making a right turn?",
 "To allow its rear wheels to clear the corner", "To pass traffic", "Because the driver is lost", "A"),
(185, T2, "You should generally pass a large truck:",
 "On the left", "On the right", "Using the shoulder", "A"),
(186, T2, "When a bus or streetcar is stopped at a safety zone, you may pass at no more than:",
 "5 mph", "10 mph", "15 mph", "B"),
(187, T2, "May you drive through a pedestrian safety zone?",
 "Yes, below 10 mph", "No", "Only if no pedestrians are present", "B"),
(188, T2, "You should turn directly in front of an approaching light-rail vehicle:",
 "If you signal", "Never", "If it is moving slowly", "B"),
(189, T2, "Light-rail vehicles on public roads generally:",
 "Have the same rights and responsibilities as other vehicles", "Must always yield to cars", "May ignore traffic signals", "A"),
(190, T2, "When an emergency vehicle approaches with red lights and siren:",
 "Pull to the right edge and stop", "Stop in your current lane", "Accelerate", "A"),
(191, T2, "If you're inside an intersection when an emergency vehicle approaches:",
 "Stop immediately", "Continue through, then pull right and stop safely", "Reverse", "B"),
(192, T2, "You must not follow an emergency vehicle using sirens/lights within:",
 "100 feet", "200 feet", "300 feet", "C"),
(193, T2, "When approaching a stationary emergency vehicle with flashing lights:",
 "Speed up", "Move over and slow down", "Stop beside it", "B"),
(194, T2, "Move-over requirements also apply to certain:",
 "Tow trucks and road-work vehicles", "Private cars with hazard lights", "Bicycles", "A"),
(195, T2, "A slow-moving vehicle emblem is generally:",
 "An orange and red triangle", "A blue circle", "A white square", "A"),
(196, T2, "Vehicles displaying this slow-moving emblem generally travel:",
 "25 mph or less", "45 mph or less", "55 mph or less", "A"),
(197, T2, "NEVs and LSVs have a maximum speed of approximately:",
 "15 mph", "25 mph", "35 mph", "B"),
(198, T2, "NEVs and LSVs are restricted from roads where the speed limit exceeds:",
 "25 mph", "35 mph", "55 mph", "B"),
(199, T2, "Is intentionally frightening horses or livestock on the road legal?",
 "Yes", "No", "Only by honking", "B"),
(200, T2, "If livestock are near the roadway:",
 "Speed past quickly", "Slow or stop and follow the handler's directions", "Continuously honk", "B"),
(201, T3, "California's Basic Speed Law requires you to:",
 "Always drive the posted speed", "Never drive faster than is safe for conditions", "Always match the fastest traffic", "B"),
(202, T3, "Most California highways have an ideal maximum of:",
 "55 mph", "65 mph", "75 mph", "B"),
(203, T3, "A two-lane undivided highway generally has a maximum of:",
 "45 mph", "55 mph", "65 mph", "B"),
(204, T3, "A vehicle towing a trailer generally has a maximum speed of:",
 "45 mph", "55 mph", "65 mph", "B"),
(205, T3, "Business and residential districts are generally:",
 "15 mph", "25 mph", "35 mph", "B"),
(206, T3, "A blind intersection generally has a speed limit of:",
 "10 mph", "15 mph", "25 mph", "B"),
(207, T3, "An alley generally has a speed limit of:",
 "10 mph", "15 mph", "25 mph", "B"),
(208, T3, "Near a school while children are outside or crossing, the normal limit within 500 feet is:",
 "15 mph", "25 mph", "35 mph", "B"),
(209, T3, "Some school zones may be posted as low as:",
 "10 mph", "15 mph", "20 mph", "B"),
(210, T3, "Yellow flashing lights on a school bus mean:",
 "Pass immediately", "Slow down and prepare to stop", "Stop and remain stopped", "B"),
(211, T3, "Red flashing lights on a school bus mean:",
 "Stop", "Slow to 15 mph", "Pass cautiously", "A"),
(212, T3, "You remain stopped for a school bus until:",
 "The children have safely crossed and red lights stop flashing", "The bus driver waves once", "Five seconds have passed", "A"),
(213, T3, "Failure to stop for a school bus can result in a fine of up to:",
 "$250", "$500", "$1,000", "C"),
(214, T3, "It may also result in driving-privilege suspension for:",
 "One month", "Six months", "One year", "C"),
(215, T3, "At an obstructed railroad crossing, the 15-mph rule applies within:",
 "50 feet", "100 feet", "200 feet", "B"),
(216, T3, "This railroad rule applies when you cannot see the tracks for how far in both directions?",
 "200 feet", "300 feet", "400 feet", "C"),
(217, T3, "When warned that a train is approaching, stop at least:",
 "5 feet from the nearest track", "15 feet", "50 feet", "B"),
(218, T3, "The crossing gate rises but red railroad lights are still flashing. You should:",
 "Cross", "Wait until the red lights stop flashing", "Follow the vehicle ahead", "B"),
(219, T3, "Should you drive around a lowered railroad gate if no train is visible?",
 "Yes", "No", "Only during daylight", "B"),
(220, T3, "If there is insufficient room to completely cross railroad tracks:",
 "Enter and wait", "Do not enter the tracks", "Stop on the tracks", "B"),
(221, T3, "If your car stalls on railroad tracks and a train is approaching:",
 "Stay in the car", "Immediately exit and move away diagonally toward the direction the train is coming from", "Push the car", "B"),
(222, T3, "After escaping a vehicle stuck on tracks with a train approaching, call:",
 "311", "511", "911", "C"),
(223, T3, "You should scan the road at least:",
 "5 seconds ahead", "10 seconds ahead", "30 seconds ahead", "B"),
(224, T3, "Normal safe following distance is at least:",
 "One second", "Three seconds", "Six seconds", "B"),
(225, T3, "A vehicle merges too closely in front of you. You should:",
 "Accelerate", "Take your foot off the accelerator to create space", "Tailgate it", "B"),
(226, T3, "If someone is tailgating you:",
 "Brake-check them", "Maintain course/speed and move right when safe to let them pass", "Accelerate above the speed limit", "B"),
(227, T3, "Blind spots are normally located:",
 "Directly in front", "To the sides slightly behind the driver", "Only behind the trunk", "B"),
(228, T3, "To check a blind spot:",
 "Depend only on mirrors", "Look over the appropriate shoulder", "Turn your whole body and steering wheel", "B"),
(229, T3, "Check your blind spot before:",
 "Changing lanes", "Merging", "Both A and B", "C"),
(230, T3, "You should also check your blind spot before opening:",
 "Your hood", "Your car door next to traffic", "Your glove box", "B"),
(231, T3, "At night, if oncoming headlights are too bright, look toward:",
 "The headlights", "The right edge of your lane", "The center line", "B"),
(232, T3, "When leaving a brightly lit area at night:",
 "Speed up", "Drive slowly until your eyes adjust", "Use emergency flashers", "B"),
(233, T3, "When only one light approaches at night:",
 "Assume it is a car", "Move as far right as possible because it could be a motorcycle/bicycle or vehicle with a missing headlight", "Drive toward the center line", "B"),
(234, T3, "On a wet road, reduce your speed by approximately:",
 "5–10 mph", "20 mph", "30 mph", "A"),
(235, T3, "On packed snow, reduce your speed by:",
 "One-quarter", "Half", "5 mph", "B"),
(236, T3, "On ice, drive no faster than approximately:",
 "5 mph", "15 mph", "25 mph", "A"),
(237, T3, "Bridges and overpasses tend to:",
 "Freeze before other road surfaces", "Freeze last", "Never freeze", "A"),
(238, T3, "Roads may be especially slippery when rain first begins because:",
 "Oil and dust mix with the water", "Tires become larger", "Road paint melts", "A"),
(239, T3, "If visibility is less than 100 feet in heavy rain or snow, do not drive faster than:",
 "20 mph", "30 mph", "40 mph", "B"),
(240, T3, "In rain, use:",
 "High beams", "Low beams", "Parking lights only", "B"),
(241, T3, "Hydroplaning occurs when:",
 "Tires lose contact with the road and ride on water", "Brakes overheat", "The engine floods", "A"),
(242, T3, "If you begin hydroplaning:",
 "Brake hard", "Slow down gradually without sudden braking", "Turn sharply", "B"),
(243, T3, "To avoid hydroplaning:",
 "Drive faster through standing water", "Slow down and avoid standing water when possible", "Use cruise control", "B"),
(244, T3, "If your vehicle skids on a slippery surface:",
 "Immediately brake hard", "Slowly release the accelerator and avoid braking", "Accelerate", "B"),
(245, T3, "During a slippery-surface skid, turn the steering wheel:",
 "In the direction of the skid", "Opposite the skid", "Randomly", "A"),
(246, T3, "In high winds, you should:",
 "Use cruise control", "Reduce speed and maintain a firm grip on the steering wheel", "Drive faster", "B"),
(247, T3, "In heavy fog, high beams should generally:",
 "Be used", "Not be used because they reflect glare back", "Be flashed continuously", "B"),
(248, T3, "In heavy fog, increase your:",
 "Following distance", "Speed", "Radio volume", "A"),
(249, T3, "If fog becomes too thick to drive safely:",
 "Continue slowly regardless", "Consider pulling off the road and using emergency flashers", "Use high beams", "B"),
(250, T3, "During a law-enforcement traffic break, you should:",
 "Pass the patrol vehicle", "Slow to the officer's speed and do not pass", "Stop immediately in your lane", "B"),
(251, T4, "California DUI laws apply to:",
 "Alcohol only", "Illegal drugs only", "Alcohol and drugs", "C"),
(252, T4, "Prescription medication can impair driving and lead to DUI:",
 "True", "False", "Only if the prescription is expired", "A"),
(253, T4, "Over-the-counter medication can also impair driving:",
 "True", "False", "Only for drivers under 21", "A"),
(254, T4, "Mixing alcohol with drugs may:",
 "Decrease your ability to drive safely", "Make driving safer", "Have no effect", "A"),
(255, T4, "For a driver age 21 or older, the illegal BAC level is:",
 "0.01%", "0.04%", "0.08%", "C"),
(256, T4, "For a driver under age 21, the illegal BAC level is:",
 "0.01%", "0.04%", "0.08%", "A"),
(257, T4, "For a person on DUI probation, the BAC threshold is:",
 "0.01%", "0.04%", "0.08%", "A"),
(258, T4, "A commercial driver's BAC threshold is:",
 "0.01%", "0.04%", "0.08%", "B"),
(259, T4, "A driver carrying passengers for hire has a BAC threshold of:",
 "0.01%", "0.04%", "0.08%", "B"),
(260, T4, "A BAC below the statutory limit guarantees that you are safe to drive:",
 "True", "False", "Only for drivers over 21", "B"),
(261, T4, "An open alcohol container should generally be stored:",
 "In the glove box", "In the trunk or an area where passengers do not sit", "Under the driver's seat", "B"),
(262, T4, "Keeping an open container of alcohol in the glove box is:",
 "Legal", "Illegal", "Legal if locked", "B"),
(263, T4, "Drinking alcohol while riding as a passenger in an ordinary vehicle is:",
 "Legal", "Illegal", "Legal above age 21", "B"),
(264, T4, "The open-container rule has exceptions for passengers in certain vehicles, including:",
 "Buses and taxis", "Motorcycles", "Ordinary sedans", "A"),
(265, T4, "By driving in California, you consent to chemical testing when lawfully required for suspected DUI:",
 "True", "False", "Only under age 21", "A"),
(266, T4, "Refusing required DUI chemical testing can result in:",
 "Suspension or revocation", "No consequence", "Only a fine", "A"),
(267, T4, "After a DUI arrest, an officer may provide a temporary driver's license for:",
 "10 days", "30 days", "90 days", "B"),
(268, T4, "Following a DUI arrest, you may request a DMV administrative hearing within:",
 "5 days", "10 days", "30 days", "B"),
(269, T4, "DUI convictions remain on your driving record for:",
 "3 years", "5 years", "10 years", "C"),
(270, T4, "Handheld cell-phone use while driving is:",
 "Safe and legal", "Unsafe and illegal", "Allowed at any speed below 25 mph", "B"),
(271, T4, "Adult drivers should use phones when necessary:",
 "In hands-free mode", "By holding the phone low", "Only with their left hand", "A"),
(272, T4, "While driving, you should read a text message:",
 "If it is short", "Never", "At a red light", "B"),
(273, T4, "If you need to make a call that cannot wait:",
 "Hold the phone near the steering wheel", "Pull safely off the road", "Slow to 15 mph", "B"),
(274, T4, "A mounted phone may be operated using:",
 "Continuous typing", "A single swipe or touch", "Both hands", "B"),
(275, T4, "A minor may normally use a hands-free phone while driving:",
 "Yes", "No", "Only after 10 p.m.", "B"),
(276, T4, "A minor may use a phone while driving for:",
 "Social media", "Emergency assistance", "Music selection", "B"),
(277, T4, "Drivers and passengers must wear:",
 "Seat belts", "Helmets", "Reflective clothing", "A"),
(278, T4, "If a passenger under age 16 is not wearing a seat belt, the driver:",
 "May receive a ticket", "Has no responsibility", "Receives only a warning", "A"),
(279, T4, "The shoulder portion of a seat belt should be worn:",
 "Under the arm", "Across the shoulder and chest", "Behind the back", "B"),
(280, T4, "The lap belt should fit:",
 "High across the stomach", "Low and snug across the hips", "Loosely across the abdomen", "B"),
(281, T4, "You should sit at least approximately how far from an airbag cover?",
 "5 inches", "10 inches", "20 inches", "B"),
(282, T4, "A child under 2, under 40 pounds, and under 3 feet 4 inches should generally be:",
 "Rear-facing", "Forward-facing", "Using only a seat belt", "A"),
(283, T4, "A rear-facing child restraint should be placed in front of an active airbag:",
 "Yes", "No", "Only on highways", "B"),
(284, T4, "Children under 8 or under 4 feet 9 inches generally require:",
 "A child passenger restraint system in a rear seat", "An adult seat belt in the front seat", "No restraint on short trips", "A"),
(285, T4, "A child six years old or younger may be left unattended in a vehicle:",
 "Whenever the engine is off", "Not unless supervised as permitted by law", "For up to 15 minutes", "B"),
(286, T4, "The supervising person for such a child must be at least:",
 "10 years old", "12 years old", "16 years old", "B"),
(287, T4, "If you are involved in a collision, you must:",
 "Stop", "Leave if the damage looks minor", "Leave if the other driver says it is okay", "A"),
(288, T4, "If someone is injured in a collision, you should:",
 "Call 911", "Wait 24 hours", "Only contact insurance", "A"),
(289, T4, "If no one is injured, you should when appropriate:",
 "Leave the vehicles blocking traffic", "Move your vehicle out of traffic", "Immediately abandon your vehicle", "B"),
(290, T4, "A collision involving injury or death must be reported to law enforcement within:",
 "12 hours", "24 hours", "10 days", "B"),
(291, T4, "A collision must be reported to DMV within 10 days if property damage exceeds:",
 "$500", "$750", "$1,000", "C"),
(292, T4, "A collision resulting in ANY injury must be reported to DMV:",
 "Only if you caused it", "Yes", "Only if an ambulance was called", "B"),
(293, T4, "The DMV collision report is called:",
 "SR 1", "DL 44", "SR 22", "A"),
(294, T4, "Does law enforcement automatically file your required SR 1 with DMV for you?",
 "Yes", "No", "Only for collisions above $5,000", "B"),
(295, T4, "An adult driver's license may be suspended for accumulating:",
 "4 points in 12 months", "5 points in 12 months", "8 points in 12 months", "A"),
(296, T4, "Another suspension threshold is:",
 "6 points in 24 months", "8 points in 24 months", "10 points in 24 months", "A"),
(297, T4, "Another suspension threshold is:",
 "6 points in 36 months", "8 points in 36 months", "12 points in 36 months", "B"),
(298, T4, "Traffic violator school may generally be used for an eligible one-point violation once every:",
 "6 months", "12 months", "18 months", "C"),
(299, T4, "After buying a vehicle, you have how many days to transfer ownership to your name?",
 "5", "10", "20", "B"),
(300, T4, "After becoming a California resident or getting a job in California, you generally have how long to register an out-of-state vehicle?",
 "10 days", "20 days", "30 days", "B"),
]

LETTER = {"A": 0, "B": 1, "C": 2}


def js_str(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    assert len(ROWS) == 200, len(ROWS)
    ids = [row[0] for row in ROWS]
    assert ids == list(range(101, 301))
    chunks = []
    for qid, topic, prompt, a, b, c, ans in ROWS:
        chunks.append(
            "\n".join(
                [
                    "  {",
                    f'    id: {qid},',
                    f'    topic: "{js_str(topic)}",',
                    f'    prompt: "{js_str(prompt)}",',
                    "    choices: [",
                    f'      "{js_str(a)}",',
                    f'      "{js_str(b)}",',
                    f'      "{js_str(c)}"',
                    "    ],",
                    f"    answer: {LETTER[ans]}",
                    "  }",
                ]
            )
        )
    print(",\n".join(chunks))


if __name__ == "__main__":
    main()
